export const POST_CUSTOMER_REGISTER_EPIC =
  'POST_CUSTOMER_REGISTER_EPIC';
export const POST_CUSTOMER_REGISTER_LOADING =
  'POST_CUSTOMER_REGISTER_LOADING';
export const POST_CUSTOMER_REGISTER_SUCCESS =
  'POST_CUSTOMER_REGISTER_SUCCESS';
export const POST_CUSTOMER_REGISTER_ERROR =
  'POST_CUSTOMER_REGISTER_ERROR';
